# Generated by Django 4.2.3 on 2023-10-10 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('creator', models.IntegerField(blank=True, null=True)),
                ('updater', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('qualification', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='doctors/profile_pic/')),
                ('department', models.CharField(choices=[('cardiology', 'Cardiology'), ('dermatology', 'Dermatology'), ('orthopedics', 'Orthopedics'), ('pediatrics', 'Pediatrics'), ('neurology', 'Neurology')])),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(blank=True, null=True)),
                ('location', models.CharField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
