# Generated by Django 4.2.3 on 2023-11-18 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='code',
            field=models.ImageField(max_length=255, upload_to=''),
        ),
    ]
